'use client';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Login from './login/page';
// import Admin from '/admin/index';
// import Employee from './employee/page';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Payroll</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/assets/Coins.png" rel="icon" />
      </Head>


      <>
        <Login/>
        {/* <Admin/> */}
      </>
 
    </div>
  );
}